

# This file was *autogenerated* from the file example3.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1)
load('../utils.sage')
C1 = x*y*z ; C2 = x**_sage_const_2 +y**_sage_const_2 +z**_sage_const_2  ; f = C1**_sage_const_2 +C2**_sage_const_3  ; C = Curve(f)

d = MinimumDegreeSyzygy(f)['mindegree_generators'][_sage_const_0 ]
d = NewDer(d)
epts = eigenscheme(d)
print(epts)
a,b,c = (_sage_const_1 ,_sage_const_2 ,_sage_const_3 ) ; l = a*x+b*y+c*z
ld = UnionDer(d,f,l)
print(ld)
lepts = eigenscheme(ld)
print(lpets)

